// server/server.js
// MongoDB (Mongoose) based backend for Online Inventory & Documents System
// FINAL VERSION — Footer on ALL pages (Option 2)
// Footer text: "Generated by L&B Company Inventory System"

const express = require('express');
const cors = require('cors');
const xlsx = require('xlsx');
const mongoose = require('mongoose');
const path = require('path');
const PDFDocument = require('pdfkit');

const app = express();
const PORT = process.env.PORT || 3000;
const MONGODB_URI = process.env.MONGODB_URI;
const SECURITY_CODE = process.env.SECRET_SECURITY_CODE || '1234';

// ===========================
// Middleware
// ===========================
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ===========================
// MongoDB Connection
// ===========================
if (!MONGODB_URI) {
  console.error("❌ ERROR: MONGODB_URI missing.");
  process.exit(1);
}

mongoose.set("strictQuery", false);
mongoose
  .connect(MONGODB_URI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(() => console.log("✅ Connected to MongoDB Atlas"))
  .catch(err => {
    console.error("MongoDB Connection Error:", err);
    process.exit(1);
  });

const { Schema } = mongoose;

// ===========================
// Schemas
// ===========================
const UserSchema = new Schema({
  username: { type: String, unique: true },
  password: String,
  createdAt: { type: Date, default: Date.now }
});
const User = mongoose.model("User", UserSchema);

const InventorySchema = new Schema({
  sku: String,
  name: String,
  category: String,
  quantity: Number,
  unitCost: Number,
  unitPrice: Number,
  createdAt: { type: Date, default: Date.now }
});
const Inventory = mongoose.model("Inventory", InventorySchema);

const DocumentSchema = new Schema({
  name: String,
  size: Number,
  date: { type: Date, default: Date.now }
});
const Doc = mongoose.model("Doc", DocumentSchema);

const ActivitySchema = new Schema({
  user: String,
  action: String,
  time: { type: Date, default: Date.now }
});
const ActivityLog = mongoose.model("ActivityLog", ActivitySchema);

// Duplicate log prevention window: 30 seconds
const DUPLICATE_WINDOW = 30 * 1000;

async function logActivity(user, action) {
  try {
    const safeUser = user || "System";
    const safeAction = action || "";
    const now = Date.now();

    const last = await ActivityLog.findOne().sort({ time: -1 }).lean();
    if (last) {
      if (
        last.user === safeUser &&
        last.action === safeAction &&
        now - new Date(last.time).getTime() <= DUPLICATE_WINDOW
      ) {
        return;
      }
    }

    await ActivityLog.create({ user: safeUser, action: safeAction });
  } catch (err) {
    console.log("logActivity error:", err);
  }
}

// ===========================
// Health Check
// ===========================
app.get("/api/test", (req, res) => {
  res.json({ success: true, message: "API Online", time: new Date() });
});

// ===========================
// AUTH
// ===========================
app.post("/api/register", async (req, res) => {
  const { username, password, securityCode } = req.body;

  if (securityCode !== SECURITY_CODE)
    return res.status(403).json({ success: false, message: "Invalid security code" });

  if (!username || !password)
    return res.status(400).json({ success: false, message: "Missing fields" });

  const exists = await User.findOne({ username }).lean();
  if (exists)
    return res.status(409).json({ success: false, message: "Username exists" });

  await User.create({ username, password });
  await logActivity("System", `Registered new user: ${username}`);

  res.json({ success: true });
});

app.post("/api/login", async (req, res) => {
  const { username, password } = req.body;

  const user = await User.findOne({ username, password }).lean();
  if (!user)
    return res.status(401).json({ success: false, message: "Invalid login" });

  await logActivity(username, "Logged in");

  res.json({ success: true, user: username });
});

// ===========================
// INVENTORY CRUD
// ===========================
app.get("/api/inventory", async (req, res) => {
  const items = await Inventory.find({}).lean();
  const normalized = items.map(i => ({ ...i, id: i._id.toString() }));
  res.json(normalized);
});

app.post("/api/inventory", async (req, res) => {
  const item = await Inventory.create(req.body);
  await logActivity(req.headers["x-username"], `Added: ${item.name}`);
  res.status(201).json({ ...item.toObject(), id: item._id.toString() });
});

app.put("/api/inventory/:id", async (req, res) => {
  const item = await Inventory.findByIdAndUpdate(req.params.id, req.body, { new: true });
  if (!item) return res.status(404).json({ message: "Not found" });

  await logActivity(req.headers["x-username"], `Updated: ${item.name}`);
  res.json({ ...item.toObject(), id: item._id.toString() });
});

app.delete("/api/inventory/:id", async (req, res) => {
  const item = await Inventory.findByIdAndDelete(req.params.id);
  if (!item) return res.status(404).json({ message: "Not found" });

  await logActivity(req.headers["x-username"], `Deleted: ${item.name}`);
  res.status(204).send();
});

// ===========================
// PDF REPORT GENERATOR
// ===========================
app.get("/api/inventory/report/pdf", async (req, res) => {
  try {
    const items = await Inventory.find({}).lean();

    const now = new Date();
    const printDate = now.toLocaleString();
    const printedBy = req.headers["x-username"] || "System";
    const reportId = `REP-${Date.now()}`;
    const filename = `Inventory_Report_${now.toISOString().slice(0, 10)}.pdf`;

    // PDF Init
    const doc = new PDFDocument({
      size: "A4",
      layout: "landscape",
      margin: 40,
      bufferPages: true
    });

    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Type", "application/pdf");

    doc.pipe(res);

    // ===========================
    // HEADER (Page 1 only)
    // ===========================
    doc.font("Helvetica-Bold").fontSize(22).text("L&B Company", 40, 40);

    doc.fontSize(10).font("Helvetica");
    doc.text("Jalan Mawar 8, Taman Bukit Beruang Permai, Melaka", 40, 70);
    doc.text("Phone: 01133127622", 40, 85);
    doc.text("Email: lbcompany@gmail.com", 40, 100);

    // Right side
    doc.font("Helvetica-Bold").fontSize(15).text("INVENTORY REPORT", 620, 40);
    doc.font("Helvetica").fontSize(10);
    doc.text(`Print Date: ${printDate}`, 620, 63);
    doc.text(`Report ID: ${reportId}`, 620, 78);
    doc.text("Status: Generated", 620, 93);
    doc.text(`Printed by: ${printedBy}`, 620, 108);

    doc.moveTo(40, 130).lineTo(800, 130).stroke();

      // ============================================
    // TABLE SETTINGS (Fixed Width — No Wrapping)
    // ============================================
    const rowHeight = 18;

    const cols = {
      sku: 40,
      name: 100,
      category: 260,
      qty: 340,
      cost: 400,
      price: 480,
      value: 560,
      revenue: 670
    };

    const widths = {
      sku: 60,
      name: 160,
      category: 80,
      qty: 60,
      cost: 80,
      price: 80,
      value: 110,
      revenue: 120
    };

    let y = 150;

    // ============================================
    // DRAW TABLE HEADER
    // ============================================
    function drawHeader() {
      doc.font("Helvetica-Bold").fontSize(10);

      doc.rect(cols.sku, y, widths.sku, rowHeight).stroke();
      doc.rect(cols.name, y, widths.name, rowHeight).stroke();
      doc.rect(cols.category, y, widths.category, rowHeight).stroke();
      doc.rect(cols.qty, y, widths.qty, rowHeight).stroke();
      doc.rect(cols.cost, y, widths.cost, rowHeight).stroke();
      doc.rect(cols.price, y, widths.price, rowHeight).stroke();
      doc.rect(cols.value, y, widths.value, rowHeight).stroke();
      doc.rect(cols.revenue, y, widths.revenue, rowHeight).stroke();

      doc.text("SKU", cols.sku + 3, y + 4);
      doc.text("Product Name", cols.name + 3, y + 4);
      doc.text("Category", cols.category + 3, y + 4);
      doc.text("Quantity", cols.qty + 3, y + 4);
      doc.text("Unit Cost", cols.cost + 3, y + 4);
      doc.text("Unit Price", cols.price + 3, y + 4);
      doc.text("Total Inventory Value", cols.value + 3, y + 4);
      doc.text("Total Potential Revenue", cols.revenue + 3, y + 4);

      y += rowHeight;
      doc.font("Helvetica").fontSize(9);
    }

    drawHeader();

    // ============================================
    // TABLE ROWS
    // ============================================
    let subtotalQty = 0;
    let totalValue = 0;
    let totalRevenue = 0;

    for (const it of items) {
      // Need new page?
      if (y + rowHeight > 510) {
        doc.addPage({ size: "A4", layout: "landscape", margin: 40 });

        // Reset y for new page
        y = 40;
        drawHeader();
      }

      const qty = Number(it.quantity || 0);
      const cost = Number(it.unitCost || 0);
      const price = Number(it.unitPrice || 0);

      const invVal = qty * cost;
      const potential = qty * price;

      subtotalQty += qty;
      totalValue += invVal;
      totalRevenue += potential;

      // Draw row cells
      doc.rect(cols.sku, y, widths.sku, rowHeight).stroke();
      doc.rect(cols.name, y, widths.name, rowHeight).stroke();
      doc.rect(cols.category, y, widths.category, rowHeight).stroke();
      doc.rect(cols.qty, y, widths.qty, rowHeight).stroke();
      doc.rect(cols.cost, y, widths.cost, rowHeight).stroke();
      doc.rect(cols.price, y, widths.price, rowHeight).stroke();
      doc.rect(cols.value, y, widths.value, rowHeight).stroke();
      doc.rect(cols.revenue, y, widths.revenue, rowHeight).stroke();

      // Fill row values
      doc.text(it.sku || "", cols.sku + 3, y + 4);
      doc.text(it.name || "", cols.name + 3, y + 4);
      doc.text(it.category || "", cols.category + 3, y + 4);
      doc.text(String(qty), cols.qty + 3, y + 4);
      doc.text(`RM ${cost.toFixed(2)}`, cols.cost + 3, y + 4);
      doc.text(`RM ${price.toFixed(2)}`, cols.price + 3, y + 4);
      doc.text(`RM ${invVal.toFixed(2)}`, cols.value + 3, y + 4);
      doc.text(`RM ${potential.toFixed(2)}`, cols.revenue + 3, y + 4);

      y += rowHeight;
    }

    // ============================================
    // TOTALS BOX — Last Page Only
    // ============================================
    function drawTotals() {
      let boxY = y + 20;
      if (boxY < 200) boxY = 200;

      const boxX = 560;
      const boxWidth = 250;
      const boxHeight = 70;

      doc.rect(boxX, boxY, boxWidth, boxHeight).stroke();

      doc.font("Helvetica-Bold").fontSize(10);
      doc.text(`Subtotal (Quantity): ${subtotalQty} units`, boxX + 10, boxY + 10);
      doc.text(`Total Inventory Value: RM ${totalValue.toFixed(2)}`, boxX + 10, boxY + 28);
      doc.text(`Total Potential Revenue: RM ${totalRevenue.toFixed(2)}`, boxX + 10, boxY + 46);
    }

    drawTotals();

    // ============================================
    // PAGE NUMBERS (all pages)
    // ============================================
    const pageRange = doc.bufferedPageRange();
    for (let i = 0; i < pageRange.count; i++) {
      doc.switchToPage(i);
      doc.font("Helvetica").fontSize(9).text(
        `Page ${i + 1} of ${pageRange.count}`,
        0,
        doc.page.height - 30,
        { align: "center" }
      );
    }

    // ============================================
    // FOOTER (ALL PAGES — Option B)
    // ============================================
    for (let i = 0; i < pageRange.count; i++) {
      doc.switchToPage(i);

      doc.font("Helvetica").fontSize(9).text(
        "Generated by L&B Company Inventory System",
        0,
        doc.page.height - 45,
        { align: "center" }
      );
    }

      // END PDF
    doc.end();

  } catch (err) {
    console.error("PDF_ERROR:", err);
    res.status(500).json({ message: "PDF generation failed" });
  }
});

// ============================================================================
// XLSX EXPORT
// ============================================================================
app.get("/api/inventory/report", async (req, res) => {
  try {
    const items = await Inventory.find({}).lean();
    const today = new Date().toISOString().slice(0, 10);
    const filename = `Inventory_Report_${today}.xlsx`;

    const wsData = [
      ["L&B Company — Inventory Report"],
      ["Date:", today],
      [],
      ["SKU", "Name", "Category", "Quantity", "Unit Cost", "Unit Price",
       "Total Inventory Value", "Total Potential Revenue"]
    ];

    let totalValue = 0, totalRevenue = 0;

    items.forEach(it => {
      const qty = Number(it.quantity || 0);
      const uc = Number(it.unitCost || 0);
      const up = Number(it.unitPrice || 0);

      const invVal = qty * uc;
      const rev = qty * up;

      totalValue += invVal;
      totalRevenue += rev;

      wsData.push([
        it.sku || "",
        it.name || "",
        it.category || "",
        qty,
        uc.toFixed(2),
        up.toFixed(2),
        invVal.toFixed(2),
        rev.toFixed(2)
      ]);
    });

    wsData.push([]);
    wsData.push(["", "", "", "Totals", "", "",
      totalValue.toFixed(2),
      totalRevenue.toFixed(2)
    ]);

    const ws = xlsx.utils.aoa_to_sheet(wsData);
    const wb = xlsx.utils.book_new();
    xlsx.utils.book_append_sheet(wb, ws, "Inventory");

    const out = xlsx.write(wb, { type: "buffer", bookType: "xlsx" });

    await Doc.create({ name: filename, size: out.length });
    await logActivity(req.headers["x-username"], "Generated XLSX Inventory Report");

    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Type",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    );
    res.send(out);

  } catch (err) {
    console.error("XLSX_ERROR:", err);
    res.status(500).json({ message: "XLSX generation failed" });
  }
});

// ============================================================================
// DOCUMENT MANAGER
// ============================================================================
app.get("/api/documents", async (req, res) => {
  const docs = await Doc.find({}).sort({ date: -1 }).lean();
  const normalized = docs.map(d => ({ ...d, id: d._id.toString() }));
  res.json(normalized);
});

app.post("/api/documents", async (req, res) => {
  const docu = await Doc.create({ ...req.body, date: new Date() });
  await logActivity(req.headers["x-username"], `Uploaded: ${docu.name}`);
  res.status(201).json({ ...docu.toObject(), id: docu._id.toString() });
});

app.delete("/api/documents/:id", async (req, res) => {
  const docu = await Doc.findByIdAndDelete(req.params.id);
  if (!docu) return res.status(404).json({ message: "Document not found" });

  await logActivity(req.headers["x-username"], `Deleted: ${docu.name}`);
  res.status(204).send();
});

app.get("/api/documents/download/:filename", (req, res) => {
  const file = req.params.filename;

  if (file.startsWith("Inventory_Report"))
    return res.redirect("/api/inventory/report");

  res.status(404).json({ message: "File not available" });
});

// ============================================================================
// ACTIVITY LOGS
// ============================================================================
app.get("/api/logs", async (req, res) => {
  const logs = await ActivityLog.find({})
    .sort({ time: -1 })
    .limit(500)
    .lean();

  const formatted = logs.map(l => ({
    user: l.user,
    action: l.action,
    time: new Date(l.time).toISOString()
  }));

  res.json(formatted);
});

// ============================================================================
// FRONTEND
// ============================================================================
app.use(express.static(path.join(__dirname, "../public")));

app.get("*", (req, res) => {
  if (req.path.startsWith("/api/"))
    return res.status(404).json({ message: "API route not found" });

  res.sendFile(path.join(__dirname, "../public/index.html"));
});

// ============================================================================
// STARTUP + SERVER LAUNCH
// ============================================================================
async function ensureDefaultAdmin() {
  const count = await User.countDocuments({});
  if (count === 0) {
    await User.create({ username: "admin", password: "password" });
    await logActivity("System", "Default admin created");
  }

  await logActivity("System", `Server started on port ${PORT}`);
}

(async () => {
  await ensureDefaultAdmin();
  console.log("🚀 Server running on port " + PORT);
  app.listen(PORT);
})();
